### ISSUE TITLE
commits name

### ISSUE THREAD

**Issue by Super-Baleine** [Ne0blast/DocSpace#1]
I think you shoudnt name your commit like #1 and so on cuz #X refers to the issues or PR.

**Comment by Ne0blast** [comment]
To manage my commits, it's the best ;) so i'll keep this form even if it's the same form for issues

**Comment by Super-Baleine** [comment]
xD
Really, I don't wanna offense you, but that's fucking stupid xD

**Comment by Ne0blast** [comment]
I know but i love it ;)

**Comment by Super-Baleine** [comment]
And I love you x)

**Comment by Ne0blast** [comment]
You can say what you want :p
